language: node_js
node_js:
 - stable
install:
 - npm install
cache:
  directories:
    - node_modules
after_success:
deploy:
 - provider: npm
   skip_cleanup: true
   email: "contact@popotojs.com"
   api_key: $NPM_TOKEN
